CVE-2011-2204
VulnerabilityHistoryProject/tomcat-vulnerabilities pull request #33
Opened 2019-10-22 20:30 UTC by Jeremy523

Completed round 1 research on Tomcat CVE-2011-2204

2019-10-22 21:01 UTC, andymeneely commented on cves/CVE-2011-2204.yml
> +nickname: JMX Information Disclosure
Your audience won't know what JMX is up front, so this isn't a catchy nickname. Go with something more down-to-earth. Or if you can't think of something you can leave it blank too.

2019-10-22 21:01 UTC, andymeneely commented on cves/CVE-2011-2204.yml
> +CWE: CWE-200 (Information exposure)
```suggestion
CWE: 200
```
(we pull the info automatically anyway)

2019-10-22 21:01 UTC, andymeneely commented on cves/CVE-2011-2204.yml
> +  sensitive information by reading a log file.
Remember your audience and that you're trying to tell the story here. A few things:

- Don't start with a definition. Nobody likes to read a dictionary.
- Remove the version numbers. They're not important to this description. 
- What's MemoryUserDatabase? This needs to be written to someone who doesn't know the codebase. This is just a thin rewriting of the CVE description. You need to use your own words more.
- Explain JMX and what it's used for. 
- `It's` - never use "it" unless you're referring to a nearby noun, otherwise your reader will get a null pointer exception trying to find that noun
- `This is because` and `This allows` - rephrase those to be more active about the actor and what they're doing.
- If sensitive data are in logs on a server somewhere, why is that so bad? Explore the risks of that more.

-

2019-10-22 21:01 UTC, andymeneely commented on cves/CVE-2011-2204.yml
> +  - commit: 763a56b45999653ce648a18462b8a826809215b1
Why isn't `eae54419c6` the VCC?

2019-10-22 23:13 UTC, Jeremy523 commented on cves/CVE-2011-2204.yml
> +  - commit: 763a56b45999653ce648a18462b8a826809215b1
I got these Git SHAs from the git commits themselves by going through the git logs. There's also the added challenge that they migrated from SVN to GIt in between, so I had to go through the revisions first. Where is `eae54419c6` coming from?

2019-10-28 04:53 UTC, cxs7700 requested changes

2019-10-28 04:53 UTC, cxs7700 commented on cves/CVE-2011-2204.yml
> +    mistake as a small coding and requirements mistake.
On lines 258 and 265, you said "Due to this" and "Given all of this". I think it is important to specify what "this" actually is for better understanding, especially when concluding a response. In general, you might also want to limit your use of "just" because it seems like a filler word.

2019-10-28 04:53 UTC, cxs7700 commented on cves/CVE-2011-2204.yml
> +    simpler than extracting out only the username field, but less secure).
I would not say that printing a toString method is simpler than extracting only the username field. I think it is the other way around because when extracting the user name field, you are printing one field as opposed to many. Either way, describing the simplicity is unnecessary information in this case because it is an issue independent of the actual vulnerability.

2019-10-28 16:47 UTC, Jeremy523 commented on cves/CVE-2011-2204.yml
> +    mistake as a small coding and requirements mistake.
Fair point, will try to be more concise

2019-10-28 16:49 UTC, Jeremy523 commented on cves/CVE-2011-2204.yml
> +    simpler than extracting out only the username field, but less secure).
I think I meant simplicity in the sense that it's conceptually easier to say "oh let's just log the whole object" instead of stopping to think about only logging the information they needed. I'll try to make this a bit clearer.

2019-11-01 14:17 UTC, iclare commented
2 upvotes

2020-02-27 19:20 UTC, merged