CVE-2011-1184
VulnerabilityHistoryProject/tomcat-vulnerabilities pull request #40
Opened 2019-10-24 04:54 UTC by Rxy8841

Updated and filled out all information, plus YAML syntax fixes

2019-10-26 20:10 UTC, exl5325 requested changes

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +    The original code had unit tests but it did not catch this vulnerability.
A bit of confusion: even if the original unit test didn't catch the issue, wouldn't the fact that a unit test was run in the first place mean that `code` should be set to `true`? Perhaps Professor @andymeneely could answer this

Another curosity bit: usually unit tests are run before they're merged into the master repo - just because a feature is new does not mean it has not been tested. I would double check to see if Apache actually did run tests for the fix

Grammar/style: avoid informal language like "gonna". The last sentence (so the automated testing....) is a fragment.

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +   They had found a seperate weakness in the Tomcat's implementation for authentication
nit: seperate -> separate

Same comment as the Chromium comment regarding vague pronouns. "They" doesn't refer to anyone in this context. You can say "Apache" in the first sentence and then use "they" for the remainder of the paragraph

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +    Users can look at traffic on a line, and get autheticated information. Then they
What does "traffic on a line" mean?

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +      nonce is usually sent and authenticated by default in security librarys. The
nit: librarys -> libraries

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +    applies: true
Good observation

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +     note: Added a function to check the nonce. The nonce is used to check if the message is old or already used. Now attackers can not use the same authentication message they found. Since the serve
The last sentence is a fragment and should be combined with the second to last sentence. Otherwise, this is a really good description that does a good job of capturing how the fix works

2019-10-26 20:10 UTC, exl5325 commented on cves/CVE-2011-1184.yml
> +  - commit: 639e20992a66d7a42fb59c974db91c8a0f730a1e
This seems to be a completed fix, so I don't think anything needs to be added to the `incomplete_fixes` section

2019-10-26 23:34 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +    The original code had unit tests but it did not catch this vulnerability.
I answered false for code, because I thought it was asking if the automated tests had tests for the vulnerability already. But I reread the description for the "code" and it seems like its only asking if there were tests for the module. 

I was saying that the nonce function is new, so there was no unit tests that was already in the automated system. I should have stated that more clearly, I see where the confusion is occurring.

2019-10-26 23:34 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +   They had found a seperate weakness in the Tomcat's implementation for authentication
I will be less vague about who did what.

2019-10-26 23:34 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +    Users can look at traffic on a line, and get autheticated information. Then they
I updated traffic on a line -> "all messages being sent between the server and client"

2019-10-26 23:34 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +  - commit: 639e20992a66d7a42fb59c974db91c8a0f730a1e
Yup misread that section!

2019-10-29 00:14 UTC, Ozay34 requested changes
This one was a bit harder to understand, I think a more detailed description up front would help with having the knowledge to fully understand everything you talk about later on.

2019-10-29 00:14 UTC, Ozay34 commented on cves/CVE-2011-1184.yml
> +    information. In this case the server will give the attacker autheticated privlidges.
This description seems relatively vague and general.  This seems to just describe a generic spoofing attack.  How does the attacker insert themselves, what information are they exactly getting? A token? Does this only affect JWT or OAuth or does this have larger repercussions? How does all of this apply to Tomcat specifically, isn't it just a vulnerability with HTTP in general? Isn't that what HTTPS fixes?

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +     note: Added a function to check the nonce. The nonce is used to check if the message is old or already used. Now attackers can not use the same authentication message they found. Since the serve
Maybe use the pipe "|" to allow for a multi lined description here so it is easier to read.  Same with the vcc.

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +    note: Complete fix! The fix above worked against the Capture replay attacks. Attackers cannot use the same autheticated message, since the system will now check the nonce and deny access to that
Is this line still needed if the fix was complete, should it just be left blank now?

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +    system for it. Now that the function is implemented, they are gonna use automated
"gonna" -> "going to"

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +   went to code review the fix, they found that there could be stale nonce values, and
explaining what nonce is and how it relates to this vulnerability would be helpful in the overall description.

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +   about 3 months ago. They came out with a solution for that problem and when they
"about 3 months ago" -> "about 3 months prior", ago is relative and seems like you are talking about today.

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +   the system would still accept them. Which run into the problem that an attacker could
The last sentence here sounds a bit weird, maybe "Which allowed attackers to ..." instead?

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +       This commit was created to add a new security functionality and fix a old one.
"fix a old one" -> "fix an old one"

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +       But it introduces a new one which they catch pretty quickly.
"catch" -> "caught"

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +     authentication.
Is this even possible? If someone manages to get your authentication token, how could you differentiate them from the original person?
"find a authenticated" -> "find an authenticated"

2019-10-29 00:14 UTC, adw4236 commented on cves/CVE-2011-1184.yml
> +      since the user will never be able to reuse.
misplaced period

2019-10-29 22:16 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +      since the user will never be able to reuse.
All Grammar problems <- FIXED

2019-10-29 22:16 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +     authentication.
This is where nonce value is used to check if the message was old or already used.

2019-10-29 22:16 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +   went to code review the fix, they found that there could be stale nonce values, and
Good catch, it is very difficult to understand without that description.

2019-10-29 22:16 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +    note: Complete fix! The fix above worked against the Capture replay attacks. Attackers cannot use the same autheticated message, since the system will now check the nonce and deny access to that
I had the line in there because I thought we had to fill it out no matter what.

2019-10-29 22:16 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +    information. In this case the server will give the attacker autheticated privlidges.
I put the emphasis on the wrong part of the sentence. The problem is not about authentication or attackers getting the messages. The problem is that the system doesn't check if the authenticated message is old and already used. I will better describe this.

2019-10-29 22:17 UTC, Rxy8841 commented on cves/CVE-2011-1184.yml
> +     note: Added a function to check the nonce. The nonce is used to check if the message is old or already used. Now attackers can not use the same authentication message they found. Since the serve
Sorry I missed that.

2020-02-27 19:16 UTC, merged