CVE-2013-4444
VulnerabilityHistoryProject/tomcat-vulnerabilities pull request #46
Opened 2019-10-25 01:41 UTC by aaa1008

Completed CVE-2013-4444 for Tomcat

2019-10-30 00:41 UTC, ath9902 commented
You could add a note for "distrustful_input" to the lesson learned.   Developers need to really carefully check things like file uploads.  Also, "complex_inputs" could apply because inputs may not match assumptions about them could also apply.

2019-10-30 18:13 UTC, AdamVD requested changes

2019-10-30 18:13 UTC, AdamVD commented on cves/CVE-2013-4444.yml
> +  The implementation allowed unrestricted reading of files without obvious
Was it not obvious that files were checked for scripting? Or were there checks missing to catch even obvious scripting? This sentence is a little confusing.

2019-10-30 18:13 UTC, AdamVD commented on cves/CVE-2013-4444.yml
> +    the issue but instead it was an overall "code cleanup" that included the fix
This is indeed quite interesting! Was the removed code completely un-used during "normal" code execution? It is interesting that this created a vulnerability, and provides additional justification to remove any "dead" code.

2019-10-30 18:14 UTC, AdamVD commented
+3 from me!

2019-11-03 16:40 UTC, aaa1008 commented on cves/CVE-2013-4444.yml
> +  The implementation allowed unrestricted reading of files without obvious
reworded. Thanks!

2019-11-03 16:41 UTC, aaa1008 commented on cves/CVE-2013-4444.yml
> +    the issue but instead it was an overall "code cleanup" that included the fix
It was used. However, commits including the fix didn't indicate that they were for fixing the issue which I personally found odd.

2020-02-20 20:19 UTC, merged