CVE-2016-0763
VulnerabilityHistoryProject/tomcat-vulnerabilities pull request #49
Opened 2019-10-25 06:15 UTC by TLezynski

2019-10-28 03:04 UTC, mesternefeld commented on cves/CVE-2016-0763.yml
> +CWE: Bad Coding Practices
Please put the CWE number if possible

2019-10-28 03:05 UTC, mesternefeld commented on cves/CVE-2016-0763.yml
> +        Was the original code unit tested, or not unit tested? Did the fix involve
Please fix it to the original

2019-10-30 16:22 UTC, akn4743 requested changes

2019-10-30 16:22 UTC, akn4743 commented on cves/CVE-2016-0763.yml
> +  answer: I was unable to find this information.
Even though you couldn't find the fix, add places where you looked. Any reputable blog or forum would be good to write down.

2019-10-30 16:22 UTC, akn4743 commented on cves/CVE-2016-0763.yml
> +nickname: global shouldn't mean globl
global*

2019-10-31 21:45 UTC, TLezynski commented on cves/CVE-2016-0763.yml
> +nickname: global shouldn't mean globl
Thanks for catching that!

2019-10-31 21:52 UTC, TLezynski commented on cves/CVE-2016-0763.yml
> +CWE: Bad Coding Practices
Added

2019-10-31 21:52 UTC, TLezynski commented on cves/CVE-2016-0763.yml
> +        Was the original code unit tested, or not unit tested? Did the fix involve
Fixed

2019-10-31 21:57 UTC, TLezynski commented on cves/CVE-2016-0763.yml
> +  answer: I was unable to find this information.
Thanks, I updated this

2019-11-01 14:32 UTC, PaceyLong commented on cves/CVE-2016-0763.yml
> +  answer: factory
Please write a full sentence.

2020-02-20 20:18 UTC, merged