CVE-2011-2729
VulnerabilityHistoryProject/tomcat-vulnerabilities pull request #53
Opened 2019-10-25 14:47 UTC by ath9902

Filled out CVE-2011-2729 tomcat vulnerability

2019-10-30 17:51 UTC, AdamVD requested changes

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +reported: 2011-09-20
The date the vulnerability was reported to the team shouldn't be after it was announced to the world (the next section). Maybe you reversed these dates?

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +description: Jsvc is an abstraction layer that allows Java applications to run UNIX more easily.  The vulnerablity in this service can allow applications to access files belonging to superuser (this
Did you mean "run **on** UNIX more easily."?

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +description: Jsvc is an abstraction layer that allows Java applications to run UNIX more easily.  The vulnerablity in this service can allow applications to access files belonging to superuser (this
```suggestion
description: Jsvc is an abstraction layer that allows Java applications to run UNIX more easily.  The vulnerablity in this service can allow applications to access files belonging to superuser (this could be password files, superuser logs, sysystem configuration, etc.).
```

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +  answer: Automated unit test were not involed in this vulnerability
```suggestion
  answer: Automated unit tests were not involved in this vulnerability.
```

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
>    code:
```suggestion
  code: false
```

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
>    fix:
```suggestion
  fix: false
```

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +reported: 2011-09-20
The contest date section shows 2011-09-20, so it is the *announced* section that requires re-investigation.

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +announced: 2011-08-12
Needs fix (see comments on *reported* section).

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +    note: wrappers around services to simplify them may have unexpected consequences. Thought must be given to wrappers for the information (both implict and explicit that it can let through)
```suggestion
    note: Wrappers around services to simplify them may have unexpected consequences. Thought must be given to wrappers for the information (both implicit and explicit that it can let through).
```

2019-10-30 17:51 UTC, AdamVD commented on cves/CVE-2011-2729.yml
> +  answer: This was identified by Wilfried Weissmann on 20 July 2011 and made public on 12 August 2011. Affects 5.5.32-5.5.33  No specifics on how it was found were listed.
Who is Wilfried Weissman? Is he a part of the team or an external security researcher?

2019-10-30 17:52 UTC, AdamVD commented
I'll give this one a +1!

2019-10-31 22:04 UTC, kzalbak commented on cves/CVE-2011-2729.yml
> +  answer: Automated unit test were not involed in this vulnerability
How do you know this?

2019-10-31 22:06 UTC, kzalbak commented on cves/CVE-2011-2729.yml
> +  answer: The requirements for the wrapper were not clearly specified.  Had they been, proper unit tests could have been developed.
I would elaborate on this a bit more - maybe talk about what kinds of unit tests would be needed or what else could have helped prevent this vulnerability.

2019-11-01 00:14 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +    note: wrappers around services to simplify them may have unexpected consequences. Thought must be given to wrappers for the information (both implict and explicit that it can let through)
Thanks for finding that spelling and capitalization mistake I'll make sure to correct it.

2019-11-01 00:16 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +description: Jsvc is an abstraction layer that allows Java applications to run UNIX more easily.  The vulnerablity in this service can allow applications to access files belonging to superuser (this
Thanks for finding that grammar mistake I'll make sure to correct it.

2019-11-01 02:41 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +reported: 2011-09-20
I accidentally put the date in the bounty section when it shouldn't have been there I will remove the date. I also fixed the reported and announced dates.

2019-11-01 02:42 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +description: Jsvc is an abstraction layer that allows Java applications to run UNIX more easily.  The vulnerablity in this service can allow applications to access files belonging to superuser (this
Thanks for finding that punctuation mistake.

2019-11-01 02:52 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +  answer: This was identified by Wilfried Weissmann on 20 July 2011 and made public on 12 August 2011. Affects 5.5.32-5.5.33  No specifics on how it was found were listed.
The page didn't specify who Wilfried Weissman I will do more research and post an update when I find out.

2019-11-01 14:43 UTC, aaa1008 commented on cves/CVE-2011-2729.yml
> +    note: Allows improper access privlidges
spelling mistake, privileges

2019-11-01 20:41 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +  answer: Automated unit test were not involed in this vulnerability
There is no evidence of unit tests. There was no test code associated with this check-in.

2019-11-01 20:47 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +  answer: The requirements for the wrapper were not clearly specified.  Had they been, proper unit tests could have been developed.
The requirements should have the wrapper inputs and outputs and their associated data types and ranges. The requirements should also include how error are handled. The unit tests could include that type safety was guaranteed. The unit test could inject a broad range of bad data and bad data types to ensure that there are no unexpected behaviors. Bad data could include bad data types, out of range values, pointers that point to other sections of memory or routines, encapsulated programs, and malware.

2019-11-01 20:48 UTC, ath9902 commented on cves/CVE-2011-2729.yml
> +    note: Allows improper access privlidges
Thanks for catching that spelling mistake I will update it right away.

2020-02-20 20:16 UTC, merged